# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
HOPE_STREAM:
  TOKEN: ${HOPE_STREAM_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
SUGGESTED_FOLLOWS:
  - kirk.graham@rivervalley.org
  - clynt.reddy@rivervalley.org
  -
    id: ce3958ae-4ffa-43a2-b71e-87ec0e68107d #Terry Parkman
  -
    id: 01ec6531-41fd-4fdf-b5c8-ad4acd870937 # Rachel Parsons
  - gabi.orourke@rivervalley.org
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  DEFAULT_VERSION: NLT
CLOUDINARY:
  URL: ${CLOUDINARY_URL}
DATABASE:
  URL: ${DATABASE_URL}

CONTENT:
  SERMON_CHANNEL_ID: 1257fa2a-c75a-4d46-9d17-ba380a57ba11
  TYPES:
    - ContentSeriesContentItem
    - DevotionalContentItem
    - MediaContentItem
    - UniversalContentItem
    - WeekendContentItem
    - ContentItem

TABS:
  HOME:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      subtitle: Daily Prayer
    - subtitle: Daily Scripture
      algorithms:
        - type: CONTENT_FEED
          arguments:
            limit: 1
            channelIds:
              - 02e774f4-d636-4c4a-8be5-e0b1067aa9fc
      type: VerticalCardList
    - subtitle: Next up in DiscipleU
      algorithms:
        - type: DISCIPLEU_NEXT_UP
          arguments:
            limit: 6
            channelIds:
              - a2598288-b8bc-4857-b281-2d72765c78de
      type: HorizontalCardList

  READ:
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - b9e06a24-507b-48dc-b331-4491dc825dcd
          limit: 3
      type: VerticalCardList
    - subtitle: Read the Bible
      type: HorizontalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 02e774f4-d636-4c4a-8be5-e0b1067aa9fc
    - subtitle: Go Kids SOAP
      type: HorizontalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 912256d6-3f4b-4af7-9939-ad1a130ce757

  WATCH:
    - subtitle: Latest Messages
      algorithms:
      - type: CONTENT_FEED
        arguments:
          limit: 5
          channelIds:
            - 1257fa2a-c75a-4d46-9d17-ba380a57ba11
      type: HeroList
      primaryAction:
        # Right now, you hardcode exactly what GraphQL should return.
        # Long term, we hope to have a more sophisticated mechanism for driving this field
        action: OPEN_CHANNEL
        title: 'All messages'
        relatedNode:
          __typename: ContentChannel
          id: 1257fa2a-c75a-4d46-9d17-ba380a57ba11
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - b336c424-ad7d-4654-ad0c-7317431d1d26
      type: HorizontalCardList
      subtitle: All Message Series
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - a2598288-b8bc-4857-b281-2d72765c78de
      type: HorizontalCardList
      subtitle: All DiscipleU Series

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
  CONNECT:
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]