# This file, in conjuction with your .env file,
# should be used to configure the apollos server.

# Any values you wish to keep secret should be placed in `.env`
# You can access those values (and any other values in your environment)
# using the ${VARIABLE_NAME} syntax

# This file should be checked into version control.
# `.env` should NOT be checked into version control.
APP:
  # This variable is used for generating deep links.
  # It should match whatver is in your Info.plist `CFBundleURLTypes`
  DEEP_LINK_HOST: ${DEEP_LINK_HOST}
  UNIVERSAL_LINK_HOST: ${UNIVERSAL_LINK_HOST}
  ROOT_API_URL: ${ROOT_URL}
  JOBS_USERNAME: ${JOBS_USERNAME}
  JOBS_PASSWORD: ${JOBS_PASSWORD}
BUGSNAG:
  API_KEY: ${BUGSNAG_KEY}
ROCK:
  URL: ${ROCK_URL}
  API_TOKEN: ${ROCK_TOKEN}
HOPE_STREAM:
  TOKEN: ${HOPE_STREAM_TOKEN}
UNIVERSAL_LINKS:
  APPLE_APP_ID: ${APPLE_APP_ID}
  APPLE_TEAM_ID: ${APPLE_TEAM_ID}
  APP_STORE_LINK: ${IOS_REDIRECT}
  PLAY_STORE_LINK: ${ANDROID_REDIRECT}
  GOOGLE_APP_ID: ${GOOGLE_APP_ID}
  GOOGLE_KEYSTORE_SHA256: ${GOOGLE_KEYSTORE_SHA256}
ONE_SIGNAL:
  APP_ID: ${ONE_SIGNAL_APP_ID}
  REST_KEY: ${ONE_SIGNAL_REST_KEY}
CHURCH_ONLINE:
  URL: ${CHURCH_ONLINE_URL}
  WEB_VIEW_URL: https://apollos.online.church/
SUGGESTED_FOLLOWS:
  - kirk.graham@rivervalley.org
  - clynt.reddy@rivervalley.org
  -
    id: ce3958ae-4ffa-43a2-b71e-87ec0e68107d #Terry Parkman
  -
    id: 01ec6531-41fd-4fdf-b5c8-ad4acd870937 # Rachel Parsons
  - gabi.orourke@rivervalley.org
  -
    id: 723f9c21-e40f-4cb1-b4df-200da4963d0e # pastor rob ketterling
ALGOLIA:
  APPLICATION_ID: ${ALGOLIASEARCH_APPLICATION_ID}
  API_KEY: ${ALGOLIASEARCH_API_KEY}
TWILIO:
  ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
  FROM_NUMBER: ${TWILIO_FROM_NUMBER}
PASS:
  TEMPLATES:
    CHECKIN: ${PWD}/wallet-passes/checkin.pass
  CERTIFICATES:
    WWDR: ${PASS_WWDR_CERT}
    SIGNER_CERT: ${PASS_SIGNER_CERT}
    SIGNER_KEY: ${PASS_SIGNER_KEY}
    SIGNER_KEY_PASSPHRASE: ${PASS_SIGNER_PASSPHRASE}
BIBLE_API:
  KEY: ${BIBLE_API_KEY}
  DEFAULT_VERSION: NLT
CLOUDINARY:
  URL: ${CLOUDINARY_URL}
DATABASE:
  URL: ${DATABASE_URL}

CONTENT:
  SERMON_CHANNEL_ID: 8aa1c855-82dc-44a1-bf22-8dd47aff9156
  TYPES:
    - ContentSeriesContentItem
    - DevotionalContentItem
    - MediaContentItem
    - UniversalContentItem
    - WeekendContentItem
    - ContentItem

TABS:
  HOME:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      subtitle: Daily Prayer
    - subtitle: 21 Days
      type: VerticalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 26cdba79-2f20-43d6-b0b2-3ba69557afaf
            limit: 1       
    - subtitle: Featured Devotional
      type: VerticalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 92d10bf9-566a-4fee-b9b0-cad4f28cc3a9
            limit: 1
    - subtitle: Daily Scripture
      algorithms:
        - type: CONTENT_FEED
          arguments:
            limit: 1
            channelIds:
              - 299478a2-2bb9-4a8c-8158-49aa6399d28f
      type: VerticalCardList
    - type: VerticalCardList
      subtitle: Seek Week
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - cc93a4c5-c205-41b8-b1b6-631eed37ee68
            limit: 1           
    - type: VerticalCardList
      subtitle: Pray for the Nations    
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 1d4b460a-19c1-415f-8785-61e97de7bfea
            limit: 1           
    - subtitle: Coming Up
      algorithms:
        - type: CONTENT_FEED
          arguments:
            limit: 2
            channelIds:
              - 63de3871-d80f-4b55-bf4e-eca67f454238
      type: VerticalCardList
    - subtitle: Next up in DiscipleU
      algorithms:
        - type: DISCIPLEU_NEXT_UP
          arguments:
            limit: 6
            channelIds:
              - 2533d86c-1e3b-4892-b8f5-7ec74c7bac79
      type: HorizontalCardList

  READ:
    - subtitle: Bible Reading
      type: HorizontalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - d74d7984-1b26-45a6-970a-5783da1d1aa6
    - subtitle: Devotionals
      type: HorizontalCardList
      algorithms:
        - type: CONTENT_FEED
          arguments:
            channelIds:
              - 92d10bf9-566a-4fee-b9b0-cad4f28cc3a9
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:92d10bf9-566a-4fee-b9b0-cad4f28cc3a9
          title: Devotionals      
    # - subtitle: 21 Days
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 26cdba79-2f20-43d6-b0b2-3ba69557afaf
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:26cdba79-2f20-43d6-b0b2-3ba69557afaf
    #       title: 21 Days    
    # - subtitle: Holy Week
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 50eb23db-694d-4199-ad05-bfc8516cff84
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:50eb23db-694d-4199-ad05-bfc8516cff84
    #       title: Holy Week
    # - subtitle: Daily SOAP
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 299478a2-2bb9-4a8c-8158-49aa6399d28f
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:299478a2-2bb9-4a8c-8158-49aa6399d28f
    #       title: Daily SOAP 
    # - subtitle: Go Kids SOAP
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 01d44686-53b0-4921-a0b2-b034d1cf05e1
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:299478a2-2bb9-4a8c-8158-49aa6399d28f
    #       title: Go Kids SOAP 
    # - subtitle: Seek Week
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - cc93a4c5-c205-41b8-b1b6-631eed37ee68
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:cc93a4c5-c205-41b8-b1b6-631eed37ee68
    #       title: Seek Week 
    # - subtitle: Pray for the Nations
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 1d4b460a-19c1-415f-8785-61e97de7bfea
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:1d4b460a-19c1-415f-8785-61e97de7bfea
    #       title: Pray for the Nations 
    # - subtitle: Promise Principle
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 518177d1-6d06-409a-af7e-2ff306f71879
    #   primaryAction:
    #     action: OPEN_CHANNEL
    #     title: 'View All'
    #     relatedNode:
    #       __typename: ContentChannel
    #       apollosId: ContentChannel:518177d1-6d06-409a-af7e-2ff306f71879
    #       title: Promise Principle
    # - subtitle: Ages Album Devotional
    #   type: HorizontalCardList
    #   algorithms:
    #     - type: CONTENT_FEED
    #       arguments:
    #         channelIds:
    #           - 99b4d840-b224-48af-8922-07aa03514f8d
      # primaryAction:
      #   action: OPEN_CHANNEL
      #   title: 'View All'
      #   relatedNode:
      #     __typename: ContentChannel
      #     apollosId: ContentChannel:99b4d840-b224-48af-8922-07aa03514f8d
      #     title: Ages Album Devotional
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - e45fda8b-0498-4cd4-a8ea-047080585afb
          limit: 6
      type: HorizontalCardList
      subtitle: Keep Reading
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:e45fda8b-0498-4cd4-a8ea-047080585afb
          title: Keep Reading

  WATCH:
    - subtitle: Latest Messages
      algorithms:
      - type: CONTENT_FEED
        arguments:
          limit: 5
          channelIds:
            - 8aa1c855-82dc-44a1-bf22-8dd47aff9156
      type: HeroList
      primaryAction:
        # Right now, you hardcode exactly what GraphQL should return.
        # Long term, we hope to have a more sophisticated mechanism for driving this field
        action: OPEN_CHANNEL
        title: 'All messages'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:8aa1c855-82dc-44a1-bf22-8dd47aff9156
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - e9db0f24-e01a-4241-bd81-3450325d7284
      type: HorizontalCardList
      subtitle: Message Series
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - 2533d86c-1e3b-4892-b8f5-7ec74c7bac79
      type: HorizontalCardList
      subtitle: DiscipleU Series
      primaryAction:
        action: OPEN_CHANNEL
        title: 'View All'
        relatedNode:
          __typename: ContentChannel
          apollosId: ContentChannel:2533d86c-1e3b-4892-b8f5-7ec74c7bac79
          title: DiscipleU Series
    - algorithms:
      - type: CONTENT_FEED
        arguments:
          channelIds:
            - ea6aad8b-78a5-43e2-9cf3-57c2bd36f8a3
      type: HorizontalCardList
      subtitle: Worship

  PRAY:
    - algorithms: [DAILY_PRAYER]
      isCard: false
      type: PrayerList
      title: Daily Prayer
    - type: VerticalPrayerList
      title: Your Prayers
  CONNECT:
    - type: FollowPeople
    - type: ActionTable
      title: Connect to Apollos
      actions:
        [
          {
            title: Google,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.google.com' },
          },
          {
            title: Facebook,
            action: OPEN_URL,
            relatedNode: { __typename: Url, url: 'https://www.facebook.com' },
          },
        ]
